weather_controllers:
    resource: '../src/services/Weather/Presentation/Controller/'
    type: attribute

subscription_controllers:
    resource: '../src/services/Subscription/Presentation/Controller/'
    type: attribute